<template>
  <!--start top-nav -->
  <div
    id="topNav"
    class="top-nav"
  >
    <ul>
      <router-link
        tag="li"
        :to="{name:'newSong'}"
      >
        <a>
          新歌
        </a>
      </router-link>
      <router-link
        tag="li"
        :to="{name:'topList'}"
      >
        <a>
          排行
        </a>
      </router-link>
      <router-link
        tag="li"
        :to="{name:'plist'}"
      >
        <a>
          歌单
        </a>
      </router-link>
      <router-link
        tag="li"
        :to="{name:'Search'}"
      >
        <a>
          搜索
        </a>
      </router-link>
    </ul>
  </div>
  <!--end top-nav -->
</template>
